#-------------------------------------------------------------------------
#Parser.py -- ATG file parser
#Compiler Generator Coco/R,
#Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
#extended by M. Loeberbauer & A. Woess, Univ. of Linz
#ported from Java to Python by Ronald Longo
#
#This program is free software; you can redistribute it and/or modify it
#under the terms of the GNU General Public License as published by the
#Free Software Foundation; either version 2, or (at your option) any
#later version.
#
#This program is distributed in the hope that it will be useful, but
#WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
#or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#for more details.
#
#You should have received a copy of the GNU General Public License along
#with this program; if not, write to the Free Software Foundation, Inc.,
#59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#As an exception, it is allowed to write an extension of Coco/R that is
#used as a plugin in non-free software.
#
#If not otherwise stated, any source code generated by Coco/R (other than
#Coco/R itself) does not fall under the GNU General Public License.
#-------------------------------------------------------------------------*/

import sys

from Scanner import Token
from Scanner import Scanner
from Scanner import Position

class ErrorRec( object ):
   def __init__( self, l, c, s ):
      self.line   = l
      self.col    = c
      self.num    = 0
      self.str    = s


class Errors( object ):
   errMsgFormat = "file %(file)s : (%(line)d, %(col)d) %(text)s\n"
   eof          = False
   count        = 0         # number of errors detected
   fileName     = ''
   listName     = ''
   mergeErrors  = False
   mergedList   = None      # PrintWriter
   errors       = [ ]
   minErrDist   = 2
   errDist      = minErrDist
      # A function with prototype: f( errorNum=None ) where errorNum is a
      # predefined error number.  f returns a tuple, ( line, column, message )
      # such that line and column refer to the location in the
      # source file most recently parsed.  message is the error
      # message corresponging to errorNum.

   @staticmethod
   def Init( fn, dir, merge, getParsingPos, errorMessages ):
      Errors.theErrors = [ ]
      Errors.getParsingPos = getParsingPos
      Errors.errorMessages = errorMessages
      Errors.fileName = fn
      listName = dir + 'listing.txt'
      Errors.mergeErrors = merge
      if Errors.mergeErrors:
         try:
            Errors.mergedList = open( listName, 'w' )
         except IOError:
            raise RuntimeError( '-- Compiler Error: could not open ' + listName )

   @staticmethod
   def storeError( line, col, s ):
      if Errors.mergeErrors:
         Errors.errors.append( ErrorRec( line, col, s ) )
      else:
         Errors.printMsg( Errors.fileName, line, col, s )

   @staticmethod
   def SynErr( errNum, errPos=None ):
      line,col = errPos if errPos else Errors.getParsingPos( )
      msg = Errors.errorMessages[ errNum ]
      Errors.storeError( line, col, msg )
      Errors.count += 1

   @staticmethod
   def SemErr( errMsg, errPos=None ):
      line,col = errPos if errPos else Errors.getParsingPos( )
      Errors.storeError( line, col, errMsg )
      Errors.count += 1

   @staticmethod
   def Warn( errMsg, errPos=None ):
      line,col = errPos if errPos else Errors.getParsingPos( )
      Errors.storeError( line, col, errMsg )

   @staticmethod
   def Exception( errMsg ):
      print errMsg
      sys.exit( 1 )

   @staticmethod
   def printMsg( fileName, line, column, msg ):
      vals = { 'file':fileName, 'line':line, 'col':column, 'text':msg }
      sys.stdout.write( Errors.errMsgFormat % vals )

   @staticmethod
   def display( s, e ):
      Errors.mergedList.write('**** ')
      for c in xrange( 1, e.col ):
         if s[c-1] == '\t':
            Errors.mergedList.write( '\t' )
         else:
            Errors.mergedList.write( ' ' )
      Errors.mergedList.write( '^ ' + e.str + '\n')

   @staticmethod
   def Summarize( sourceBuffer ):
      if Errors.mergeErrors:
         # Initialize the line iterator
         srcLineIter = iter(sourceBuffer)
         srcLineStr  = srcLineIter.next( )
         srcLineNum  = 1

         try:
            # Initialize the error iterator
            errIter = iter(Errors.errors)
            errRec  = errIter.next( )

            # Advance to the source line of the next error
            while srcLineNum < errRec.line:
               Errors.mergedList.write( '%4d %s\n' % (srcLineNum, srcLineStr) )

               srcLineStr = srcLineIter.next( )
               srcLineNum += 1

            # Write out all errors for the current source line
            while errRec.line == srcLineNum:
               Errors.display( srcLineStr, errRec )

               errRec = errIter.next( )
         except:
            pass

         # No more errors to report
         try:
            # Advance to end of source file
            while True:
               Errors.mergedList.write( '%4d %s\n' % (srcLineNum, srcLineStr) )

               srcLineStr = srcLineIter.next( )
               srcLineNum += 1
         except:
            pass

         Errors.mergedList.write( '\n' )
         Errors.mergedList.write( '%d errors detected\n' % Errors.count )
         Errors.mergedList.close( )

      sys.stdout.write( '%d errors detected\n' % Errors.count )
      if (Errors.count > 0) and Errors.mergeErrors:
         sys.stdout.write( 'see ' + Errors.listName + '\n' )


class Parser( object ):
   _EOF = 0
   _comparables = 1
   _identifier = 2
   _boolean = 3
   _print = 4
   _result = 5
   _assign = 6
   _mul = 7
   _div = 8
   _plu = 9
   _min = 10
   _inc = 11
   _dec = 12
   _blockStart = 13
   _blockEnd = 14
   _if = 15
   _cycleStart = 16
   _cycleEnd = 17
   _comma = 18
   _number = 19
   _newline = 20
   maxT = 24

   T          = True
   x          = False
   minErrDist = 2

   # Create an array of 1000 memory registers
   VARS = [ 0 ] * 1000

   def getSpix( self ):
      varName = self.token.val.upper()   # Grab the most recently parsed lexeme

      if len(varName) >= 2:
         return 26*(ord(varName[1])-ord('A'))+(ord(varName[0])-ord('A'))
      else:
         return ord(varName[0])-ord('A')

   def getNumber( self ):
      return float(self.token.val)

   def newVar( self, spix ):
      self.VARS[ spix ] = 0

   def getVar( self, spix ):
      return self.VARS[ spix ]

   def writeVal( self, val ):
      print(val)

   def setVar( self, spix, val ):
      self.VARS[ spix ] = val

   def shouldWrite(self):
     self._shouldWrite = True

   def writeValIfShould(self, spix):
     if self._shouldWrite:
       self.writeVal(self.getVar(spix))
       self._shouldWrite = False


   def __init__( self ):
      self.scanner     = None
      self.token       = None           # last recognized token
      self.la          = None           # lookahead token
      self.genScanner  = False
      self.tokenString = ''             # used in declarations of literal tokens
      self.noString    = '-none-'       # used in declarations of literal tokens
      self.errDist     = Parser.minErrDist

   def getParsingPos( self ):
      return self.la.line, self.la.col

   def SynErr( self, errNum ):
      if self.errDist >= Parser.minErrDist:
         Errors.SynErr( errNum )

      self.errDist = 0

   def SemErr( self, msg ):
      if self.errDist >= Parser.minErrDist:
         Errors.SemErr( msg )

      self.errDist = 0

   def Warning( self, msg ):
      if self.errDist >= Parser.minErrDist:
         Errors.Warn( msg )

      self.errDist = 0

   def Successful( self ):
      return Errors.count == 0;

   def LexString( self ):
      return self.token.val

   def LookAheadString( self ):
      return self.la.val

   def Get( self ):
      while True:
         self.token = self.la
         self.la = self.scanner.Scan( )
         if self.la.kind <= Parser.maxT:
            self.errDist += 1
            break
         
         self.la = self.token

   def Expect( self, n ):
      if self.la.kind == n:
         self.Get( )
      else:
         self.SynErr( n )

   def StartOf( self, s ):
      return self.set[s][self.la.kind]

   def ExpectWeak( self, n, follow ):
      if self.la.kind == n:
         self.Get( )
      else:
         self.SynErr( n )
         while not self.StartOf(follow):
            self.Get( )

   def WeakSeparator( self, n, syFol, repFol ):
      s = [ False for i in xrange( Parser.maxT+1 ) ]
      if self.la.kind == n:
         self.Get( )
         return True
      elif self.StartOf(repFol):
         return False
      else:
         for i in xrange( Parser.maxT ):
            s[i] = self.set[syFol][i] or self.set[repFol][i] or self.set[0][i]
         self.SynErr( n )
         while not s[self.la.kind]:
            self.Get( )
         return self.StartOf( syFol )

   def ALNG( self ):
      self.GENERALSTATEMENT()
      if (self.StartOf(1)):
         self.GENERALSTATEMENT()

   def GENERALSTATEMENT( self ):
      if self.la.kind == 15 or self.la.kind == 16:
         self.BLOCKSTATEMENT()
      elif self.la.kind == 2 or self.la.kind == 4 or self.la.kind == 5:
         self.LINESTATEMENT()
      else:
         self.SynErr(25)

   def BLOCKSTATEMENT( self ):
      if self.la.kind == 16:
         self.CYCLESTATEMENT()
      elif self.la.kind == 15:
         self.CONDITIONSTATEMENT()
      else:
         self.SynErr(26)

   def LINESTATEMENT( self ):
      if self.la.kind == 5:
         self.RESULTSTATEMENT()
      elif self.la.kind == 2 or self.la.kind == 4:
         self.NONRESULTSTATEMENT()
      else:
         self.SynErr(27)

   def CYCLESTATEMENT( self ):
      self.Expect(16)
      if (self.la.kind == 2 or self.la.kind == 4 or self.la.kind == 5):
         self.LINESTATEMENT()
      self.Expect(18)
      if (self.la.kind == 5):
         self.RESULTSTATEMENT()
      self.Expect(18)
      if (self.la.kind == 2 or self.la.kind == 4 or self.la.kind == 5):
         self.LINESTATEMENT()
      self.Expect(17)
      self.Expect(13)
      self.GENERALSTATEMENT()
      if (self.StartOf(1)):
         self.GENERALSTATEMENT()
      self.Expect(14)

   def CONDITIONSTATEMENT( self ):
      self.Expect(15)
      self.RESULTSTATEMENT()
      self.Expect(13)
      self.GENERALSTATEMENT()
      if (self.StartOf(1)):
         self.GENERALSTATEMENT()
      self.Expect(14)

   def RESULTSTATEMENT( self ):
      self.Expect(5)
      self.LOWESTEXR()
      self.Expect(20)

   def NONRESULTSTATEMENT( self ):
      while self.la.kind == 4:
         self.Get( )

      self.IDENTIFIER()
      self.Expect(6)
      self.LOWESTEXR()
      self.Expect(20)

   def LOWESTEXR( self ):
      self.LOWEXPR()
      while self.la.kind == 1:
         self.Get( )
         self.LOWEXPR()


   def IDENTIFIER( self ):
      self.Expect(2)
      if (self.la.kind == 22):
         self.Get( )
         self.Expect(2)
         self.Expect(23)

   def LOWEXPR( self ):
      self.HIGHEXPR()
      while self.la.kind == 9 or self.la.kind == 10:
         if self.la.kind == 9:
            self.Get( )
            self.HIGHEXPR()
         else:
            self.Get( )
            self.HIGHEXPR()


   def HIGHEXPR( self ):
      self.VALUE()
      while self.la.kind == 7 or self.la.kind == 8:
         if self.la.kind == 7:
            self.Get( )
            self.VALUE()
         else:
            self.Get( )
            self.VALUE()


   def VALUE( self ):
      if self.la.kind == 2 or self.la.kind == 11 or self.la.kind == 12:
         while self.la.kind == 11 or self.la.kind == 12:
            self.UNARYOPERATION()

         self.IDENTIFIER()
      elif self.la.kind == 19:
         self.Get( )
      elif self.la.kind == 3:
         self.Get( )
      elif self.la.kind == 21:
         self.Get( )
         self.LOWEXPR()
         self.Expect(17)
      else:
         self.SynErr(28)

   def UNARYOPERATION( self ):
      if self.la.kind == 11:
         self.Get( )
      elif self.la.kind == 12:
         self.Get( )
      else:
         self.SynErr(29)



   def Parse( self, scanner ):
      self.scanner = scanner
      self.la = Token( )
      self.la.val = u''
      self.Get( )
      self.ALNG()
      self.Expect(0)


   set = [
      [T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x],
      [x,x,T,x, T,T,x,x, x,x,x,x, x,x,x,T, T,x,x,x, x,x,x,x, x,x]

      ]

   errorMessages = {
      
      0 : "EOF expected",
      1 : "comparables expected",
      2 : "identifier expected",
      3 : "boolean expected",
      4 : "print expected",
      5 : "result expected",
      6 : "assign expected",
      7 : "mul expected",
      8 : "div expected",
      9 : "plu expected",
      10 : "min expected",
      11 : "inc expected",
      12 : "dec expected",
      13 : "blockStart expected",
      14 : "blockEnd expected",
      15 : "if expected",
      16 : "cycleStart expected",
      17 : "cycleEnd expected",
      18 : "comma expected",
      19 : "number expected",
      20 : "newline expected",
      21 : "\"(\" expected",
      22 : "\"{\" expected",
      23 : "\"}\" expected",
      24 : "??? expected",
      25 : "invalid GENERALSTATEMENT",
      26 : "invalid BLOCKSTATEMENT",
      27 : "invalid LINESTATEMENT",
      28 : "invalid VALUE",
      29 : "invalid UNARYOPERATION",
      }


